version: "2"

run:
    allow-parallel-runners: true
    allow-serial-runners: true

output:
    formats:
        text:
            path: stdout

linters:
    enable:
        - bodyclose
        - decorder
        - errcheck
        - errorlint
        - goconst
        - gocyclo
        - govet
        - ineffassign
        - misspell
        - nakedret
        - nilerr
        - revive
        - staticcheck
    settings:
        decorder:
            dec-order:
                - const
                - var
                - type
                - func
            ignore-underscore-vars: false
            disable-dec-num-check: false
            disable-type-dec-num-check: false
            disable-const-dec-num-check: false
            disable-var-dec-num-check: false
            disable-dec-order-check: false
            disable-init-func-first-check: false
        revive:
            severity: error
            enable-all-rules: true
            rules:
                -   name: argument-limit
                    arguments: [10]
                    exclude: ['**/*_test.go']
                -   name: function-result-limit
                    arguments: [3]
                    exclude: ['**/*_test.go']
                -   name: function-length
                    exclude: ['**/*_test.go']
                -   name: cognitive-complexity
                    arguments: [15]
                    exclude: ['**/*_test.go']
                -   name: cyclomatic
                    arguments: [15]
                    exclude: ['**/*_test.go']
                -   name: line-length-limit
                    arguments: [130]
                -   name: add-constant
                    disabled: true
                -   name: exported
                    disabled: true
                -   name: error-strings
                    disabled: true
                -   name: comment-spacings
                    disabled: true
                -   name: flag-parameter
                    disabled: true
                -   name: get-return
                    disabled: true
                -   name: package-comments
                    disabled: true
                -   name: unchecked-type-assertion
                    disabled: true
                -   name: import-alias-naming
                    disabled: true
                -   name: max-public-structs
                    disabled: true
                -   name: nested-structs
                    disabled: true
                -   name: unsecure-url-scheme
                    disabled: true
                -   name: epoch-naming
                    disabled: true
                -   name: struct-tag
        staticcheck:
            checks:
                - ST1005
    exclusions:
        generated: lax
        paths:
            - mocks
            - third_party$
            - builtin$
            - examples$

formatters:
    enable:
        - goimports
    settings:
        goimports:
            local-prefixes:
                - github.com/fascari/token-swap-workbench
    exclusions:
        generated: lax
        paths:
            - mocks
            - third_party$
            - builtin$
            - examples$
